# Generated by Django 2.0.6 on 2018-08-10 04:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Announcement text')),
                ('send_date', models.DateTimeField(help_text='Announcement send date and time should be later than the current date and time', verbose_name='Announcement date and time')),
                ('send_for_elite', models.BooleanField(verbose_name='Send only to elite participants')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'marathon_announcement',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementChronotrackTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(help_text='The announcement about Chronotrack events will be sent to the mobile app users using this template', verbose_name='Template text')),
            ],
            options={
                'verbose_name': 'Announcement Chronotrack template',
                'verbose_name_plural': 'Announcement Chronotrack templates',
                'db_table': 'marathon_announcement_ct_template',
            },
        ),
    ]
