# Generated by Django 2.0.6 on 2018-07-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marathon_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonRunner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_external', models.BigIntegerField(verbose_name='Id of runner got from client')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.TextField(max_length=100, verbose_name='Last name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('citizenship', models.CharField(max_length=200, verbose_name='Citizenship')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('user_register_date', models.DateField(verbose_name='Registration date')),
                ('second_phone', models.CharField(max_length=50, verbose_name='Second phone')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('emergency_contact', models.CharField(max_length=150, verbose_name='Emergency contact name')),
                ('emergency_phone', models.CharField(max_length=50, verbose_name='Emergency contact phone')),
                ('t_shirt_size', models.CharField(max_length=20, verbose_name='T-shirt size')),
                ('running_club', models.CharField(max_length=200, verbose_name='Running club')),
                ('is_disabled', models.NullBooleanField(verbose_name='Is runner a disabled person')),
                ('is_prof', models.BooleanField(verbose_name='Is runner a professional sportsman')),
                ('is_child', models.BooleanField(verbose_name='Is runner a child')),
                ('is_elite', models.BooleanField(verbose_name='Is runner an elite sportsman')),
                ('marathon_registration_datetime', models.DateTimeField(verbose_name='Registration time')),
                ('cluster_run_letter', models.CharField(max_length=10, verbose_name='Run cluster letter')),
                ('runner_number', models.IntegerField(verbose_name='Runner number')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marathon_common.Marathon', verbose_name='Marathon in which runner participates')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marathon_common.MarathonRoute', verbose_name='Route which runner will run on')),
            ],
            options={
                'db_table': 'marathon_runner',
            },
        ),
        migrations.RunSQL('ALTER TABLE marathon_runner ADD COLUMN user_load text DEFAULT "current_user"();'),
        migrations.RunSQL('ALTER TABLE marathon_runner ADD COLUMN time_load timestamp without time zone DEFAULT now();'),
    ]
