# Generated by Django 2.0.6 on 2018-08-10 04:19

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=2048, verbose_name='Photo frame image')),
            ],
            options={
                'verbose_name': 'Expo map',
                'verbose_name_plural': 'Expo maps',
                'db_table': 'marathon_expo_map',
            },
        ),
        migrations.CreateModel(
            name='ExpoStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stand name')),
                ('website', models.URLField(verbose_name='Website')),
                ('text', tinymce.models.HTMLField(verbose_name='Stand description, special offers, etc')),
                ('top_left_x', models.IntegerField(verbose_name='X of top left corner of expo stand on the map image')),
                ('top_left_y', models.IntegerField(verbose_name='Y of top left corner of expo stand on the map image')),
                ('width', models.IntegerField(verbose_name='Width of the expo stand on the map image')),
                ('height', models.IntegerField(verbose_name='Height of the expo stand on the map image')),
            ],
            options={
                'verbose_name': 'Expo stand',
                'verbose_name_plural': 'Expo stands',
                'db_table': 'marathon_expo_stand',
            },
        ),
    ]
