# Generated by Django 2.0.6 on 2018-07-01 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Danger type')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='How is the incident severe', max_length=100, verbose_name='Incident severity')),
            ],
        ),
        migrations.CreateModel(
            name='SignalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='When happened', verbose_name='Time happened')),
                ('coords', models.CharField(help_text='Where happened', max_length=20, verbose_name='Signal coordinates')),
                ('description', models.TextField(blank=True, help_text='What happened', verbose_name='Incident description')),
                ('ambulance_required', models.BooleanField(help_text='Is ambulance required', verbose_name='Ambulance requirement')),
                ('status', models.CharField(choices=[('new', 'New'), ('wip', 'In progress'), ('res', 'Resolved')], default='new', help_text='signal status', max_length=3, verbose_name='Signal status')),
            ],
        ),
        migrations.CreateModel(
            name='DangerIncident',
            fields=[
                ('signalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marathon_signal.SignalBase')),
            ],
            bases=('marathon_signal.signalbase',),
        ),
        migrations.CreateModel(
            name='DangerSeverity',
            fields=[
                ('incidentseverity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marathon_signal.IncidentSeverity')),
            ],
            bases=('marathon_signal.incidentseverity',),
        ),
        migrations.CreateModel(
            name='MedicalIncident',
            fields=[
                ('signalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marathon_signal.SignalBase')),
            ],
            bases=('marathon_signal.signalbase',),
        ),
        migrations.CreateModel(
            name='MedicalSeverity',
            fields=[
                ('incidentseverity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marathon_signal.IncidentSeverity')),
            ],
            bases=('marathon_signal.incidentseverity',),
        ),
        migrations.AddField(
            model_name='signalbase',
            name='initiator',
            field=models.ForeignKey(help_text='From whom', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member initiator'),
        ),
        migrations.AddField(
            model_name='medicalincident',
            name='severity',
            field=models.ForeignKey(help_text='How much the incident is severe', on_delete=django.db.models.deletion.CASCADE, to='marathon_signal.MedicalSeverity', verbose_name='Incident severity'),
        ),
        migrations.AddField(
            model_name='dangerincident',
            name='severity',
            field=models.ForeignKey(help_text='How much the incident is severe', on_delete=django.db.models.deletion.CASCADE, to='marathon_signal.DangerSeverity', verbose_name='Incident severity'),
        ),
        migrations.AddField(
            model_name='dangerincident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_signal.DangerType', verbose_name='Incident type'),
        ),
    ]
