# Generated by Django 2.0.6 on 2018-08-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_marathons', '0001_initial'),
        ('marathon_chronotrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_time', models.IntegerField(verbose_name='Chip time of a runner')),
            ],
            options={
                'verbose_name': 'Runner result',
                'verbose_name_plural': 'Runner results',
                'db_table': 'ct_result',
            },
        ),
        migrations.RemoveField(
            model_name='ctintervalresult',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='ctintervalresult',
            name='runner',
        ),
        migrations.AddField(
            model_name='ctbracket',
            name='ct_bracket_id',
            field=models.IntegerField(default=0, verbose_name='Bracket id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctinterval',
            name='ct_interval_id',
            field=models.IntegerField(default=0, verbose_name='Chronotrack interval id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctinterval',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marathon_marathons.MarathonRoute', verbose_name='Marathon route of the interval'),
        ),
        migrations.DeleteModel(
            name='CtIntervalResult',
        ),
        migrations.AddField(
            model_name='ctresult',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_chronotrack.CtBracket', verbose_name='Bracket for which results are measured'),
        ),
        migrations.AddField(
            model_name='ctresult',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_chronotrack.CtInterval', verbose_name='Interval of the result measurement'),
        ),
        migrations.AddField(
            model_name='ctresult',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_chronotrack.MarathonRunner', verbose_name='Runner for which results are measured'),
        ),
    ]
