# Generated by Django 2.0.6 on 2018-08-10 11:26

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marathon_marathons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cannot be edited', max_length=256, verbose_name='Menu item name used in server code')),
                ('title', models.CharField(help_text='You can dynamically change menu of the mobile app from here. Changing title of a menu item will change the menu item title in the hamburger menu.', max_length=256, verbose_name='Menu item title text')),
                ('text', tinymce.models.HTMLField(verbose_name='Contents of a page shown when user clicks menu item')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'db_table': 'marathon_menu_item',
            },
        ),
        migrations.CreateModel(
            name='MenuItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Menu item group title')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_marathons.MarathonRoute', verbose_name='Route for which menu content is set')),
            ],
            options={
                'verbose_name': 'Menu item group',
                'verbose_name_plural': 'Menu item groups',
                'db_table': 'marathon_menu_item_group',
            },
        ),
        migrations.CreateModel(
            name='PhotoFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=2048, verbose_name='Photo frame image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Photo frame',
                'verbose_name_plural': 'Photo frames',
                'db_table': 'marathon_photo_frame',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marathon_common.MenuItemGroup', verbose_name='Menu item group'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon_marathons.MarathonRoute', verbose_name='Route for which menu content is set'),
        ),
    ]
