# Generated by Django 2.0.6 on 2018-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Title of a marathon')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Time when all marathon activities start')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Time when all marathon activities end')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'db_table': 'marathon',
            },
        ),
        migrations.RunSQL('ALTER TABLE marathon ADD COLUMN user_load text DEFAULT "current_user"();'),
        migrations.RunSQL('ALTER TABLE marathon ADD COLUMN time_load timestamp without time zone DEFAULT now();'),
    ]
