# Generated by Django 2.0.6 on 2018-08-07 03:48

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('send_date', models.DateTimeField(help_text='Announcement send date and time should be later than the current date and time', verbose_name='Announcement date and time')),
                ('send_for_elite', models.BooleanField(verbose_name='Send only to elite participants')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'marathon_announcement',
            },
        ),
        migrations.CreateModel(
            name='ExpoStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stand name')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('top_left_x', models.IntegerField(verbose_name='X of top left corner of expo stand on the map image')),
                ('top_left_y', models.IntegerField(verbose_name='Y of top left corner of expo stand on the map image')),
                ('width', models.IntegerField(verbose_name='Width of the expo stand on the map image')),
                ('height', models.IntegerField(verbose_name='Height of the expo stand on the map image')),
            ],
            options={
                'verbose_name': 'Expo stand',
                'verbose_name_plural': 'Expo stand',
                'db_table': 'marathon_expo_stand',
            },
        ),
        migrations.CreateModel(
            name='PhotoFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=2048, verbose_name='Photo frame image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Photo frame',
                'verbose_name_plural': 'Photo frames',
                'db_table': 'marathon_photo_frame',
            },
        ),
    ]
