# Generated by Django 2.0.6 on 2018-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Title of a marathon'),
        ),
        migrations.AlterField(
            model_name='marathonroute',
            name='name',
            field=models.CharField(max_length=1044, verbose_name='Route title'),
        ),
    ]
