# Generated by Django 2.0.6 on 2018-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Route title')),
                ('map_url', models.CharField(max_length=2083, verbose_name='Url of a map created using Yandex Maps constructor')),
                ('is_active', models.BooleanField(verbose_name='Is active?')),
            ],
            options={
                'db_table': 'marathon_route',
            },
        ),
        migrations.RunSQL('ALTER TABLE marathon_route ADD COLUMN user_load text DEFAULT "current_user"();'),
        migrations.RunSQL('ALTER TABLE marathon_route ADD COLUMN time_load timestamp without time zone DEFAULT now();'),
    ]
