# Generated by Django 2.0.6 on 2018-08-11 19:10

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObjectIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=256, verbose_name='Object type name')),
                ('image', filebrowser.fields.FileBrowseField(max_length=2048, verbose_name='Icon image for map object')),
            ],
            options={
                'verbose_name': 'Map object icon',
                'verbose_name_plural': 'Map object icons',
                'db_table': 'marathon_map_icon',
            },
        ),
    ]
