# Generated by Django 2.0.6 on 2018-07-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_common', '0002_auto_20180723_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marathon',
            options={'verbose_name': 'Marathon', 'verbose_name_plural': 'Marathons'},
        ),
        migrations.AlterModelOptions(
            name='marathonroute',
            options={'verbose_name': 'Marathon route', 'verbose_name_plural': 'Marathon routes'},
        ),
    ]
